// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgTranslator.Data;

namespace TgTranslator.Migrations
{
    [DbContext(typeof(TgTranslatorContext))]
    [Migration("20200607220622_BlacklistMigration")]
    partial class BlacklistMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TgTranslator.Models.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnName("group_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("language")
                        .HasColumnType("text")
                        .HasDefaultValueSql("'en'::text");

                    b.Property<int>("TranslationMode")
                        .HasColumnName("translation_mode")
                        .HasColumnType("integer");

                    b.HasKey("GroupId")
                        .HasName("groups_pk");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("TgTranslator.Models.GroupsBlacklist", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnName("group_id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("added_at")
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("timezone('utc'::text, now())");

                    b.HasKey("GroupId")
                        .HasName("groups_blacklist_pk");

                    b.HasIndex("GroupId")
                        .IsUnique()
                        .HasName("groups_blacklist_group_id_uindex");

                    b.ToTable("groups_blacklist");
                });

            modelBuilder.Entity("TgTranslator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("integer");

                    b.Property<bool>("PmAllowed")
                        .HasColumnName("pm_allowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Track")
                        .HasColumnName("track")
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users");
                });

            modelBuilder.Entity("TgTranslator.Models.GroupsBlacklist", b =>
                {
                    b.HasOne("TgTranslator.Models.Group", "Group")
                        .WithOne("GroupsBlacklist")
                        .HasForeignKey("TgTranslator.Models.GroupsBlacklist", "GroupId")
                        .HasConstraintName("groups_blacklist_groups_group_id_fk")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
