// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TgTranslator.Data;

namespace TgTranslator.Migrations
{
    [DbContext(typeof(TgTranslatorContext))]
    partial class TgTranslatorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TgTranslator.Models.Group", b =>
                {
                    b.Property<long>("GroupId")
                        .HasColumnName("group_id")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnName("language")
                        .HasColumnType("text")
                        .HasDefaultValueSql("'en'::text");

                    b.Property<int>("TranslationMode")
                        .HasColumnName("translation_mode")
                        .HasColumnType("integer");

                    b.HasKey("GroupId")
                        .HasName("groups_pkey");

                    b.ToTable("groups");
                });

            modelBuilder.Entity("TgTranslator.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnName("user_id")
                        .HasColumnType("integer");

                    b.Property<bool>("PmAllowed")
                        .HasColumnName("pm_allowed")
                        .HasColumnType("boolean");

                    b.Property<string>("Track")
                        .HasColumnName("track")
                        .HasColumnType("text");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
