<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ResXFileCodeGenerator_NullForgivingOperators>true</ResXFileCodeGenerator_NullForgivingOperators>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Catglobe.ResXFileCodeGenerator" Version="4.1.2" PrivateAssets="all" />
    <PackageReference Include="BitFaster.Caching" Version="2.6.1" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="Flurl" Version="4.0.0" />
    <PackageReference Include="Flurl.Http" Version="4.0.2" />
    <PackageReference Include="IPAddressRange" Version="6.3.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
    <PackageReference Include="OpenTelemetry.Exporter.Prometheus.AspNetCore" Version="1.19.1-beta.1" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="Sentry" Version="6.11.1" />
    <PackageReference Include="Sentry.AspNetCore" Version="6.11.1" />
    <PackageReference Include="Sentry.Serilog" Version="6.11.1" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.12" />
    <PackageReference Include="Telegram.Bot" Version="22.10.3.1" />
    <PackageReference Include="Telegram.Bot.AspNetCore" Version="22.5.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="languages.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>

    <Content Remove="appsettings.json" />
    <None Include="appsettings.json">
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>

    <None Update="blacklists.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
</Project>
